version: '3.7'
services:
  master:
    image: mcognie/maximecognie-cp22:tortoisebot-ros1-real-base
    build:
      context: .
      dockerfile: tortoisebot-ros1-real-base.Dockerfile
    hostname: master
    restart: always
    privileged: true
    network_mode: "host"
    environment:
      - ROS_MASTER_URI=http://$ROS_HOSTNAME:11311
      - ROS_HOSTNAME=$ROS_HOSTNAME
    ports:
       - "11311:11311"
    command: export ROS_HOSTNAME=192.168.1.16 && roscore

  bringup:
    image: mcognie/maximecognie-cp22:tortoisebot-ros1-real
    build:
      context: .
      dockerfile: tortoisebot-ros1-real.Dockerfile
    hostname: bringup
    depends_on:
      - master
    restart: always
    environment: 
      - LD_LIBRARY_PATH=:/opt/vc/lib
      - ROS_MASTER_URI=http://$ROS_HOSTNAME:11311
      - ROS_HOSTNAME=$ROS_HOSTNAME
    volumes:
      - /opt/vc:/opt/vc
    privileged: true
    network_mode: "host"
    devices:
      - /dev/gpiomem:/dev/gpiomem
      - /dev/mem:/dev/mem
      - /dev/vchiq:/dev/vchiq
      - /dev/ttyUSB0:/dev/ttyUSB0
    command: export ROS_HOSTNAME=192.168.1.16 && roslaunch tortoisebot_firmware bringup.launch
  
  slam:
    image: mcognie/maximecognie-cp22:tortoisebot-ros1-slam-real
    build:
      context: .
      dockerfile: tortoisebot-ros1-slam-real.Dockerfile
    depends_on:
      - bringup
    restart: always
    privileged: true
    network_mode: "host"
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment: 
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=http://$ROS_HOSTNAME:11311
      - ROS_HOSTNAME=$ROS_HOSTNAME
    command: export ROS_HOSTNAME=192.168.1.16 && roslaunch tortoisebot_slam tortoisebot_slam.launch
  
  server-bringup:
    image: mcognie/maximecognie-cp22:tortoisebot-ros1-slam-real
    build:
      context: .
      dockerfile: tortoisebot-ros1-slam-real.Dockerfile
    depends_on:
      - bringup
    restart: always
    privileged: true
    network_mode: "host"
    environment: 
      - ROS_MASTER_URI=http://$ROS_HOSTNAME:11311
      - ROS_HOSTNAME=$ROS_HOSTNAME
    command: export ROS_HOSTNAME=192.168.1.16 && roslaunch tortoisebot_firmware server_bringup.launch
